public:
  rebirth: true
  selector: 
    - node: BtActPatrol
    - node: BtActIdle
    - node: BtActPursue
    - node: BtActAttack
    - node: BtActFlee

dungeon:
  rebirth: false
  selector: 
    - node: BtActPatrol
    - node: BtActIdle
    - node: BtActPursue
    - node: BtActAttack
    - node: BtActFlee

