// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto_id.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Net {

  /// <summary>Holder for reflection information generated from proto_id.proto</summary>
  public static partial class ProtoIdReflection {

    #region Descriptor
    /// <summary>File descriptor for proto_id.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5wcm90b19pZC5wcm90bxIDTmV0KtgQCgVNc2dJZBIICgROb25lEAASFQoR",
            "TUlfTmV0d29ya0Nvbm5lY3QQARIXChNNSV9OZXR3b3JrQ29ubmVjdGVkEAIS",
            "FAoQTUlfTmV0d29ya0xpc3RlbhADEhcKE01JX05ldHdvcmtMaXN0ZW5LZXkQ",
            "BBIYChRNSV9OZXR3b3JrRGlzY29ubmVjdBAKEhoKFk1JX05ldHdvcmtEaXNj",
            "b25uZWN0RXgQCxIfChtNSV9OZXR3b3JrUmVxdWVzdERpc2Nvbm5lY3QQFBIW",
            "ChJNSV9SZW1vdmVDb21wb25lbnQQMhIWChJNSV9DcmVhdGVDb21wb25lbnQQ",
            "MxITCg9NSV9DcmVhdGVTeXN0ZW0QNBILCgdNSV9QaW5nEGUSEgoOTUlfQXBw",
            "UmVnaXN0ZXIQZhISCg5NSV9BcHBJbmZvU3luYxBnEhYKEk1JX0FwcEluZm9M",
            "aXN0U3luYxBoEhUKEEMyTF9BY2NvdW50Q2hlY2sQ6AcSFwoSQzJMX0FjY291",
            "bnRDaGVja1JzEOkHEiEKHE1JX0FjY291bnRRdWVyeU9ubGluZVRvUmVkaXMQ",
            "6gcSIwoeTUlfQWNjb3VudFF1ZXJ5T25saW5lVG9SZWRpc1JzEOsHEhkKFEwy",
            "REJfUXVlcnlQbGF5ZXJMaXN0EPIHEhsKFkwyREJfUXVlcnlQbGF5ZXJMaXN0",
            "UnMQ8wcSEwoOTDJDX1BsYXllckxpc3QQ9AcSFQoQQzJMX0NyZWF0ZVBsYXll",
            "chD2BxIXChJDMkxfQ3JlYXRlUGxheWVyUnMQ9wcSFgoRTDJEQl9DcmVhdGVQ",
            "bGF5ZXIQ+AcSGAoTTDJEQl9DcmVhdGVQbGF5ZXJScxD5BxIVChBDMkxfU2Vs",
            "ZWN0UGxheWVyEPoHEhcKEkMyTF9TZWxlY3RQbGF5ZXJScxD7BxIZChRNSV9M",
            "b2dpblRva2VuVG9SZWRpcxD+BxIbChZNSV9Mb2dpblRva2VuVG9SZWRpc1Jz",
            "EP8HEhIKDUwyQ19HYW1lVG9rZW4QgAgSFQoQQzJHX0xvZ2luQnlUb2tlbhDM",
            "CBIXChJDMkdfTG9naW5CeVRva2VuUnMQzQgSGAoTTUlfR2FtZVRva2VuVG9S",
            "ZWRpcxDOCBIaChVNSV9HYW1lVG9rZW5Ub1JlZGlzUnMQzwgSFQoQRzJEQl9R",
            "dWVyeVBsYXllchDQCBIXChJHMkRCX1F1ZXJ5UGxheWVyUnMQ0QgSEwoORzJD",
            "X1N5bmNQbGF5ZXIQ0ggSFQoQRzJNX1JlcXVlc3RXb3JsZBDUCBIUCg9HMlNf",
            "Q3JlYXRlV29ybGQQ1QgSEAoLTUlfVGVsZXBvcnQQ1ggSFQoQTUlfVGVsZXBv",
            "cnRBZnRlchDXCBITCg5HMlNfU3luY1BsYXllchDYCBIaChVHMlNfUmVxdWVz",
            "dFN5bmNQbGF5ZXIQ2QgSFAoPRzJEQl9TYXZlUGxheWVyENoIEhUKEEcyU19S",
            "ZW1vdmVQbGF5ZXIQ2wgSEwoOQzJHX0VudGVyV29ybGQQ3AgSEwoORzJNX1F1",
            "ZXJ5V29ybGQQ3QgSFQoQRzJNX1F1ZXJ5V29ybGRScxDeCBITCg5TMkNfRW50",
            "ZXJXb3JsZBDdCxITCg5TMkdfU3luY1BsYXllchDeCxITCg5TMkNfUm9sZUFw",
            "cGVhchDfCxIWChFTMkNfUm9sZURpc0FwcGVhchDgCxINCghDMlNfTW92ZRDh",
            "CxINCghTMkNfTW92ZRDiCxIcChdNSV9Ccm9hZGNhc3RDcmVhdGVXb3JsZBDR",
            "DxIhChxNSV9Ccm9hZGNhc3RDcmVhdGVXb3JsZFByb3h5ENIPEhkKFE1JX1dv",
            "cmxkU3luY1RvR2F0aGVyELkXEh4KGU1JX1dvcmxkUHJveHlTeW5jVG9HYXRo",
            "ZXIQuhcSIAobTUlfQWNjb3VudFN5bmNPbmxpbmVUb1JlZGlzEKEfEiIKHU1J",
            "X0FjY291bnREZWxldGVPbmxpbmVUb1JlZGlzEKIfEh8KGk1JX1BsYXllclN5",
            "bmNPbmxpbmVUb1JlZGlzEKMfEiEKHE1JX1BsYXllckRlbGV0ZU9ubGluZVRv",
            "UmVkaXMQpB8SFgoRTUlfUm9ib3RTeW5jU3RhdGUQiScSEwoOTUlfUm9ib3RD",
            "cmVhdGUQiicSEQoMTUlfSHR0cEJlZ2luEJBOEhkKFE1JX0h0dHBJbm5lclJl",
            "c3BvbnNlEJFOEhYKEU1JX0h0dHBSZXF1ZXN0QmFkEJJOEhgKE01JX0h0dHBS",
            "ZXF1ZXN0TG9naW4Qk04SDwoKTUlfSHR0cEVuZBCDUhIYChNNSV9IdHRwT3V0",
            "ZXJSZXF1ZXN0EIRSEhkKFE1JX0h0dHBPdXRlclJlc3BvbnNlEIVSEhIKDE1J",
            "X0NtZFRocmVhZBChnAESDwoJTUlfQ21kQXBwEKKcARIWChBNSV9DbWRXb3Js",
            "ZFByb3h5EKOcARIRCgtNSV9DbWRXb3JsZBCknAESEgoMTUlfQ21kQ3JlYXRl",
            "EKWcARIWChBNSV9DbWRFZmZpY2llbmN5EKacARITCg1NSV9FZmZpY2llbmN5",
            "EKecARIWChBTMkNfRnNtU3luY1N0YXRlELLqARIWChBDMlNfRnNtU3luY1N0",
            "YXRlELPqARIZChNDMlNfUGxheWVyU3luY1N0YXRlELTqARIZChNTMkNfUGxh",
            "eWVyU3luY1N0YXRlELXqARIPCglDMlNfRW5lbXkQtuoBEg8KCVMyQ19FbmVt",
            "eRC36gESGgoUQzJTX1JlcXVlc3RTeW5jRW5lbXkQuOoBEhoKFFMyQ19SZXF1",
            "ZXN0U3luY0VuZW15ELnqARIbChVTMkNfUmVxdWVzdExpbmtQbGF5ZXIQuuoB",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Net.MsgId), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgId {
    /// <summary>
    /// proto3的枚举，第一个必为0
    /// </summary>
    [pbr::OriginalName("None")] None = 0,
    /// <summary>
    /// 请求连接
    /// </summary>
    [pbr::OriginalName("MI_NetworkConnect")] MiNetworkConnect = 1,
    /// <summary>
    /// 连接成功
    /// </summary>
    [pbr::OriginalName("MI_NetworkConnected")] MiNetworkConnected = 2,
    /// <summary>
    /// 网络监听到一个连接
    /// </summary>
    [pbr::OriginalName("MI_NetworkListen")] MiNetworkListen = 3,
    /// <summary>
    /// 对网络监听进行一个Key值描述
    /// </summary>
    [pbr::OriginalName("MI_NetworkListenKey")] MiNetworkListenKey = 4,
    /// <summary>
    ///
    /// 物理网络的断开，network通知上层网络关闭事件
    /// 关闭可能是监听，可能是连接，根据协议体数据而定
    /// </summary>
    [pbr::OriginalName("MI_NetworkDisconnect")] MiNetworkDisconnect = 10,
    [pbr::OriginalName("MI_NetworkDisconnectEx")] MiNetworkDisconnectEx = 11,
    /// <summary>
    ///
    /// 逻辑层的断开，上层逻辑发起的主动断开网络的协议 to network
    /// 该协议没有协议体
    /// </summary>
    [pbr::OriginalName("MI_NetworkRequestDisconnect")] MiNetworkRequestDisconnect = 20,
    /// <summary>
    /// remove Component
    /// </summary>
    [pbr::OriginalName("MI_RemoveComponent")] MiRemoveComponent = 50,
    /// <summary>
    /// 创建Component
    /// </summary>
    [pbr::OriginalName("MI_CreateComponent")] MiCreateComponent = 51,
    /// <summary>
    /// 创建System
    /// </summary>
    [pbr::OriginalName("MI_CreateSystem")] MiCreateSystem = 52,
    [pbr::OriginalName("MI_Ping")] MiPing = 101,
    /// <summary>
    /// app 注册到 mgr
    /// </summary>
    [pbr::OriginalName("MI_AppRegister")] MiAppRegister = 102,
    /// <summary>
    /// app 数据同步
    /// </summary>
    [pbr::OriginalName("MI_AppInfoSync")] MiAppInfoSync = 103,
    /// <summary>
    /// app 数据同步
    /// </summary>
    [pbr::OriginalName("MI_AppInfoListSync")] MiAppInfoListSync = 104,
    /// <summary>
    /// login
    /// </summary>
    [pbr::OriginalName("C2L_AccountCheck")] C2LAccountCheck = 1000,
    /// <summary>
    ///   AccountCheckRs to client
    /// </summary>
    [pbr::OriginalName("C2L_AccountCheckRs")] C2LAccountCheckRs = 1001,
    /// <summary>
    /// 2.验证账号：验证账号之前，向Redis询问是已在其他的Login登录验证账号
    /// </summary>
    [pbr::OriginalName("MI_AccountQueryOnlineToRedis")] MiAccountQueryOnlineToRedis = 1002,
    [pbr::OriginalName("MI_AccountQueryOnlineToRedisRs")] MiAccountQueryOnlineToRedisRs = 1003,
    /// <summary>
    /// 1.选择角色：PlayerList 
    /// </summary>
    [pbr::OriginalName("L2DB_QueryPlayerList")] L2DbQueryPlayerList = 1010,
    /// <summary>
    ///   
    /// </summary>
    [pbr::OriginalName("L2DB_QueryPlayerListRs")] L2DbQueryPlayerListRs = 1011,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("L2C_PlayerList")] L2CPlayerList = 1012,
    /// <summary>
    /// 2.选择角色：没有角色，请求创建角色
    /// </summary>
    [pbr::OriginalName("C2L_CreatePlayer")] C2LCreatePlayer = 1014,
    /// <summary>
    ///   CreatePlayerRs to client
    /// </summary>
    [pbr::OriginalName("C2L_CreatePlayerRs")] C2LCreatePlayerRs = 1015,
    /// <summary>
    /// 3.选择角色：创建角色ToDB
    /// </summary>
    [pbr::OriginalName("L2DB_CreatePlayer")] L2DbCreatePlayer = 1016,
    /// <summary>
    ///   CreatePlayerToDB
    /// </summary>
    [pbr::OriginalName("L2DB_CreatePlayerRs")] L2DbCreatePlayerRs = 1017,
    /// <summary>
    /// 4.选择角色 SelectPlayer
    /// </summary>
    [pbr::OriginalName("C2L_SelectPlayer")] C2LSelectPlayer = 1018,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("C2L_SelectPlayerRs")] C2LSelectPlayerRs = 1019,
    /// <summary>
    /// 1.请求登录的Token
    /// </summary>
    [pbr::OriginalName("MI_LoginTokenToRedis")] MiLoginTokenToRedis = 1022,
    /// <summary>
    ///   GameRequestTokenToRedisRs
    /// </summary>
    [pbr::OriginalName("MI_LoginTokenToRedisRs")] MiLoginTokenToRedisRs = 1023,
    /// <summary>
    /// 2.将token和Game发送给客户端，GameToken
    /// </summary>
    [pbr::OriginalName("L2C_GameToken")] L2CGameToken = 1024,
    /// <summary>
    /// game
    /// </summary>
    [pbr::OriginalName("C2G_LoginByToken")] C2GLoginByToken = 1100,
    /// <summary>
    ///   LoginByToken
    /// </summary>
    [pbr::OriginalName("C2G_LoginByTokenRs")] C2GLoginByTokenRs = 1101,
    /// <summary>
    /// 2.登录：Game请求登录的Token
    /// </summary>
    [pbr::OriginalName("MI_GameTokenToRedis")] MiGameTokenToRedis = 1102,
    /// <summary>
    ///   ameRequestTokenToRedis
    /// </summary>
    [pbr::OriginalName("MI_GameTokenToRedisRs")] MiGameTokenToRedisRs = 1103,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("G2DB_QueryPlayer")] G2DbQueryPlayer = 1104,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("G2DB_QueryPlayerRs")] G2DbQueryPlayerRs = 1105,
    /// <summary>
    /// 玩家初次整体同步数据
    /// </summary>
    [pbr::OriginalName("G2C_SyncPlayer")] G2CSyncPlayer = 1106,
    /// <summary>
    /// 进入地图：如果本地没有实例，向AppMgr请求
    /// </summary>
    [pbr::OriginalName("G2M_RequestWorld")] G2MRequestWorld = 1108,
    /// <summary>
    /// 进入地图，请求创建地图
    /// </summary>
    [pbr::OriginalName("G2S_CreateWorld")] G2SCreateWorld = 1109,
    /// <summary>
    /// 进入地图：开始跳转，player 设为 只读
    /// </summary>
    [pbr::OriginalName("MI_Teleport")] MiTeleport = 1110,
    /// <summary>
    ///   TeleportAfter 如果跳转失败，恢复本地player，如果成功，删除本地数据
    /// </summary>
    [pbr::OriginalName("MI_TeleportAfter")] MiTeleportAfter = 1111,
    /// <summary>
    /// 同步数据到Space
    /// </summary>
    [pbr::OriginalName("G2S_SyncPlayer")] G2SSyncPlayer = 1112,
    /// <summary>
    /// 请求同步数据
    /// </summary>
    [pbr::OriginalName("G2S_RequestSyncPlayer")] G2SRequestSyncPlayer = 1113,
    [pbr::OriginalName("G2DB_SavePlayer")] G2DbSavePlayer = 1114,
    [pbr::OriginalName("G2S_RemovePlayer")] G2SRemovePlayer = 1115,
    /// <summary>
    /// 进入地图，玩家请求进入某地图
    /// </summary>
    [pbr::OriginalName("C2G_EnterWorld")] C2GEnterWorld = 1116,
    /// <summary>
    /// 进入地图：如果没有实例，向AppMgr请求
    /// </summary>
    [pbr::OriginalName("G2M_QueryWorld")] G2MQueryWorld = 1117,
    [pbr::OriginalName("G2M_QueryWorldRs")] G2MQueryWorldRs = 1118,
    /// <summary>
    /// space
    /// </summary>
    [pbr::OriginalName("S2C_EnterWorld")] S2CEnterWorld = 1501,
    /// <summary>
    /// 同步数据给Game    	
    /// </summary>
    [pbr::OriginalName("S2G_SyncPlayer")] S2GSyncPlayer = 1502,
    /// <summary>
    /// 玩家出现
    /// </summary>
    [pbr::OriginalName("S2C_RoleAppear")] S2CRoleAppear = 1503,
    /// <summary>
    /// 玩家消失
    /// </summary>
    [pbr::OriginalName("S2C_RoleDisAppear")] S2CRoleDisAppear = 1504,
    /// <summary>
    /// 玩家移动
    /// </summary>
    [pbr::OriginalName("C2S_Move")] C2SMove = 1505,
    [pbr::OriginalName("S2C_Move")] S2CMove = 1506,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("MI_BroadcastCreateWorld")] MiBroadcastCreateWorld = 2001,
    /// <summary>
    /// 进入地图，创建地图Proxy广播
    /// </summary>
    [pbr::OriginalName("MI_BroadcastCreateWorldProxy")] MiBroadcastCreateWorldProxy = 2002,
    /// <summary>
    /// Sync
    /// </summary>
    [pbr::OriginalName("MI_WorldSyncToGather")] MiWorldSyncToGather = 3001,
    /// <summary>
    /// world proxy
    /// </summary>
    [pbr::OriginalName("MI_WorldProxySyncToGather")] MiWorldProxySyncToGather = 3002,
    /// <summary>
    /// redis
    /// </summary>
    [pbr::OriginalName("MI_AccountSyncOnlineToRedis")] MiAccountSyncOnlineToRedis = 4001,
    /// <summary>
    /// 删除 account online 标志
    /// </summary>
    [pbr::OriginalName("MI_AccountDeleteOnlineToRedis")] MiAccountDeleteOnlineToRedis = 4002,
    /// <summary>
    /// 设置 account online 标志
    /// </summary>
    [pbr::OriginalName("MI_PlayerSyncOnlineToRedis")] MiPlayerSyncOnlineToRedis = 4003,
    /// <summary>
    /// 删除 account online 标志
    /// </summary>
    [pbr::OriginalName("MI_PlayerDeleteOnlineToRedis")] MiPlayerDeleteOnlineToRedis = 4004,
    /// <summary>
    /// robot
    /// </summary>
    [pbr::OriginalName("MI_RobotSyncState")] MiRobotSyncState = 5001,
    /// <summary>
    /// 请求创建Robot
    /// </summary>
    [pbr::OriginalName("MI_RobotCreate")] MiRobotCreate = 5002,
    /// <summary>
    /// http listen 的请求（外部请求）
    /// </summary>
    [pbr::OriginalName("MI_HttpBegin")] MiHttpBegin = 10000,
    /// <summary>
    /// 响应数据
    /// </summary>
    [pbr::OriginalName("MI_HttpInnerResponse")] MiHttpInnerResponse = 10001,
    [pbr::OriginalName("MI_HttpRequestBad")] MiHttpRequestBad = 10002,
    [pbr::OriginalName("MI_HttpRequestLogin")] MiHttpRequestLogin = 10003,
    [pbr::OriginalName("MI_HttpEnd")] MiHttpEnd = 10499,
    /// <summary>
    /// http connector 的消息（内部请求，外部返回）
    /// </summary>
    [pbr::OriginalName("MI_HttpOuterRequest")] MiHttpOuterRequest = 10500,
    /// <summary>
    /// 外部响应数据
    /// </summary>
    [pbr::OriginalName("MI_HttpOuterResponse")] MiHttpOuterResponse = 10501,
    /// <summary>
    /// cmd
    /// </summary>
    [pbr::OriginalName("MI_CmdThread")] MiCmdThread = 20001,
    [pbr::OriginalName("MI_CmdApp")] MiCmdApp = 20002,
    [pbr::OriginalName("MI_CmdWorldProxy")] MiCmdWorldProxy = 20003,
    [pbr::OriginalName("MI_CmdWorld")] MiCmdWorld = 20004,
    /// <summary>
    /// appmgr: the infomation of create
    /// </summary>
    [pbr::OriginalName("MI_CmdCreate")] MiCmdCreate = 20005,
    [pbr::OriginalName("MI_CmdEfficiency")] MiCmdEfficiency = 20006,
    [pbr::OriginalName("MI_Efficiency")] MiEfficiency = 20007,
    /// <summary>
    /// AI
    /// </summary>
    [pbr::OriginalName("S2C_FsmSyncState")] S2CFsmSyncState = 30002,
    [pbr::OriginalName("C2S_FsmSyncState")] C2SFsmSyncState = 30003,
    [pbr::OriginalName("C2S_PlayerSyncState")] C2SPlayerSyncState = 30004,
    [pbr::OriginalName("S2C_PlayerSyncState")] S2CPlayerSyncState = 30005,
    [pbr::OriginalName("C2S_Enemy")] C2SEnemy = 30006,
    [pbr::OriginalName("S2C_Enemy")] S2CEnemy = 30007,
    [pbr::OriginalName("C2S_RequestSyncEnemy")] C2SRequestSyncEnemy = 30008,
    [pbr::OriginalName("S2C_RequestSyncEnemy")] S2CRequestSyncEnemy = 30009,
    [pbr::OriginalName("S2C_RequestLinkPlayer")] S2CRequestLinkPlayer = 30010,
  }

  #endregion

}

#endregion Designer generated code
